fishpi-client:
  base-url: https://fishpi.cn
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0
  # 账号
  username: mitu2
  # 密码
  password: You password
  # 二次认证 如有在填写
  # mfaCode: You mfaCode
jobs:
  # 领取昨日活跃任务
  - name: receive-rewards-daily-job
    target: ink.metoo.auto.fishpi.job.ReceiveRewardsDailyJob
    # 是否启动 true 启动 false 关闭
    enable: true
    # 每日上午9点领取
    cron: 0 0 9 * * ?
    # 启动是否立即执行
    start-execute: true
  # 监听活跃度
  - name: watch-liveness-job
    target: ink.metoo.auto.fishpi.job.WatchLivenessJob
    # 是否启动 true 启动 false 关闭 (如关闭这个会可能导致其他Job失效)
    enable: true
    # 每30秒监听一次
    cron: 0/30 * * * * ?
    # 启动是否立即执行
    start-execute: false
  # 自动发送消息
  - name: auto-send-message-job
    target: ink.metoo.auto.fishpi.job.AutoSendMessageJob
    # 是否启动 true 启动 false 关闭
    enable: true
    # 9点到18点每5分钟执行一次
    cron: 0 0/10 9-18 * * ?
    # 启动是否立即执行
    start-execute: false
  # 自动阅读文章 (15活跃度)
  - name: auto-read-article-job
    target: ink.metoo.auto.fishpi.job.AutoReadArticleJob
    enable: true
    # 每日10点
    cron: 0 0 10 * * ?
    # 启动是否立即执行
    start-execute: false
  # 自动点赞文章 （6 活跃度）
  - name: auto-like-article-job
    target: ink.metoo.auto.fishpi.job.AutoLikeArticleJob
    enable: true
    # 每日10点10分
    cron: 0 10 10 * * ?
    # 启动是否立即执行
    start-execute: false
chat-room:
  # 客户端ID
  client-id: Other/<Mitu2 Technology>
  # 是否自动抢红包
  watch-red-packet: true
  # 消息队列
  message-queue:
    # 每日只发送一次条件
    - type: DAY_ONCE
      messages:
        - 小冰 去打劫
        - 鸽 行行好吧
    # 每次启动发送一次
    - type: START_ONCE
      messages: [ ]
    # 重复发送
    - type: REPEAT
      messages: [ ]
    # 按照星期几发送
    - type: WEEK
      condition: 1
      messages:
        - 周一了，这波怎么说
    - type: WEEK
      condition: 2
      messages:
        - 周二了，这波怎么说
    - type: WEEK
      condition: 3
      messages:
        - 周三了，这波怎么说
    - type: WEEK
      # 星期几 （1...7 星期一到日）
      condition: 4
      messages:
        - 周四了，我是秦始皇，V我50我去召唤兵马俑
    - type: WEEK
      condition: 5
      messages:
        - 熬过周五就周六辣
    - type: WEEK
      condition: 6
      messages:
        - 周六了，牛马们

