fishpi-client:
  base-url: https://fishpi.cn
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0
  # 账号
  username: mitu2
  # 密码
  password: You password
  # 二次认证 如有在填写
  # mfaCode: You mfaCode
jobs:
  # 领取昨日活跃任务
  - name: receive-rewards-daily-job
    target: ink.metoo.auto.fishpi.job.ReceiveRewardsDailyJob
    # 是否启动 true 启动 false 关闭
    enable: true
    # 每日上午9点领取
    cron: 0 0 9 * * ?
    # 启动是否立即执行
    start-execute: true
  # 监听活跃度
  - name: watch-liveness-job
    target: ink.metoo.auto.fishpi.job.WatchLivenessJob
    # 是否启动 true 启动 false 关闭 (如关闭这个会可能导致其他Job失效)
    enable: true
    # 每30秒监听一次
    cron: 0/30 * * * * ?
    # 启动是否立即执行
    start-execute: false
  # 自动发送消息
  - name: auto-send-message-job
    target: ink.metoo.auto.fishpi.job.AutoSendMessageJob
    # 是否启动 true 启动 false 关闭
    enable: true
    # 9点到18点每5分钟执行一次
    cron: 0 0/5 9-18 * * ?
    # 启动是否立即执行
    start-execute: false
  # 自动阅读文章
  - name: auto-read-article-job
    target: ink.metoo.auto.fishpi.job.AutoReadArticleJob
    enable: true
    # 每日10点
    cron: 0 0 10 * * ?
    # 启动是否立即执行
    start-execute: false
chat-room:
  # 客户端ID
  client-id: Other/<Mitu2 Technology>
  # 是否自动抢红包
  watch-red-packet: true
  # 消息队列
  message-queue:
    # 每日只发送一次条件
    - type: DAY_ONCE
      messages:
        - 小冰 去打劫
        - 鸽 行行好吧
    # 每次启动发送一次
    - type: START_ONCE
      messages: []
    # 重复发送
    - type: REPEAT
      messages:
        - 乌拉
        - 羡慕了
        - 好好好
        - 不愧是你
        - 小冰 亲密度
        - 小冰 活跃
        - 小冰 背包
        - 小冰 盲盒统计
        - 小冰 查询保底
        - 鸽 勇士题
        - 鸽 排行榜
        - 鸽 问题库状态
        - 鸽 乞讨概率
        - 鸽 乞讨记录
        - 鸽 坚持不懈
        - 鸽 谁最非
        - 鸽 谁最欧
        - "![图片表情](https://file.fishpi.cn/2025/01/7CB49DE24B64A960D36CA2B248BDAA22-5da22391.gif)"
        - "![图片表情](https://file.fishpi.cn/2025/01/b7f563eb1aeb32449e2632112cba77b3-bb3643ee.gif)"
        - "![图片表情](https://file.fishpi.cn/2025/01/5f7eea3f2eb98c687c27b75fb81c03a9-84513ba7.jpg)"
        - "![图片表情](https://file.fishpi.cn/2025/01/872F9BC1C7DE37F2DFCAEC5F82B1E908-dc98c35e.gif)"
        - "![图片表情](https://file.fishpi.cn/2024/11/4bb9cdb4fb6084426463733173f6bdd7-6b43ef10.gif)"
        - "![图片表情](https://file.fishpi.cn/2024/07/QQ%E5%9B%BE%E7%89%8720240715130128-58120d55.gif)"
    # 按照星期几发送
    - type: WEEK
      condition: 1
      messages:
        - 周一了，这波怎么说
    - type: WEEK
      condition: 2
      messages:
        - 周二了，这波怎么说
    - type: WEEK
      condition: 3
      messages:
        - 周三了，这波怎么说
    - type: WEEK
      # 星期几 （1...7 星期一到日）
      condition: 4
      messages:
#        - 凌 V50
        - 周四了，我是秦始皇，V我50我去召唤兵马俑
    - type: WEEK
      condition: 5
      messages:
#        - 凌 TGIF
        - 熬过周五就周六辣
    - type: WEEK
      condition: 6
      messages:
#        - 凌 窝囊费
        - 周六了，牛马们

